//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Pessoas
{
    public int Id { get; set; }
    public string Nome { get; set; }
}

public partial class Usuarios
{
    public System.Guid ID { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string IDFacebook { get; set; }
    public string CPF { get; set; }
    public int Tipo { get; set; }
    public string Matricula { get; set; }
    public System.DateTime DataNascimento { get; set; }
    public string Senha { get; set; }
    public string ConfirmaSenha { get; set; }
    public System.DateTime Data { get; set; }
    public string NumeroInscricao { get; set; }
    public string NumeroMatricula { get; set; }
    public Nullable<System.DateTime> DataMatricula { get; set; }
    public string Instituicao { get; set; }
    public string Campus { get; set; }
    public string Curso { get; set; }
    public string origem { get; set; }
}
